[package]
name = "bit-iter"
version = "0.1.0"
authors = ["Christian Tamblyn <ctamblyn76@gmail.com>"]
edition = "2018"
description = "A simple crate which allows iteration over the set bits in an integral value."
license = "MIT"

[dependencies]
