[package]
name = "check_no_std"
version = "0.1.0"
authors = ["Christian Tamblyn <ctamblyn76@gmail.com>"]
edition = "2018"

[dependencies]
bit-iter = { path = ".." }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
